ALTER TABLE `client` 
CHANGE COLUMN `appid` `appid` VARCHAR(100) NULL DEFAULT NULL ,
ADD COLUMN `domain` VARCHAR(100) NULL AFTER `appid`,
DROP INDEX `APPID` ,
ADD UNIQUE INDEX `APPID_DOMAIN` (`appid` ASC, `domain` ASC);
